print('')
print('')
print('')
print('   SQL injection weakness checklist')
print('+----------------------+-------------+')
print('|    attack method     |   weakness  |')
print('| ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ |')
print('|      Tautologies     |     safe    |')
print('|----------------------|-------------|')
print('|     Union Query      |     safe    |')
print('|----------------------|-------------|')
print('|  Piggy-Backed Query  |     safe    |')
print('+----------------------+-------------+')
